# Generated by Django 6.0.6 on 2026-07-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('en_direct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Actualite',
                'verbose_name_plural': 'Actualites',
                'ordering': ['-date_pub'],
            },
        ),
    ]
